const std = @import("std");

pub fn build(b: *std.Build) !void {
    const optimize = b.standardOptimizeOption(.{});
    const target = std.zig.CrossTarget{
        .cpu_arch = .x86,
        .os_tag = .windows,
        .abi = .msvc,
    };
    const use_llvm = true;
    const use_lld = true;

    // try b.runBuild(@import("./Compiler/build.zig"));

    // TODO: Remove `skip_dll_export`.
    const skip_dll_export = b.option(bool, "skip_dll_export", "Skip verifying that DllExport members match what is expected") orelse true;
    const hardcoded_xml = b.option(bool, "hardcoded_xml", "Hardcode XML values into the DLL to allow more optimization opportunities") orelse false;
    const final_release = b.option(bool, "final_release", "Remove debugging instruments that should not be present in a release build.") orelse false;
    const profiling = b.option(bool, "enable_profiling", "Enable profiling instrumentation") orelse false;
    const oos_logging = b.option(bool, "oos_logging", "Enable OOS logging") orelse false;

    // TODO: Set up final release workflow

    // TODO: Create custom step for codegen scripts to integrate with `std.Build.Cache`.

    // TODO: Rewrite DllExport verification script in Zig.
    const perl_dll_export = b.addSystemCommand(&.{ "perl", "-X", "bin/DllExport.pl", "DLLSources" });
    perl_dll_export.has_side_effects = true;
    perl_dll_export.setName("DllExport.pl");

    const perl_xml_validation = b.addSystemCommand(&.{ "perl", "bin/xml_validation.pl" });
    perl_xml_validation.has_side_effects = true;
    perl_xml_validation.setName("xml_validation.pl");

    const perl_cpp_line_checker = b.addSystemCommand(&.{ "perl", "bin/CPP_line_checker.pl" });
    perl_cpp_line_checker.has_side_effects = true;
    perl_cpp_line_checker.setName("CPP_line_checker.pl");

    const perl_xml_enum_global_types = b.addSystemCommand(&.{ "perl", "bin/xml_enum_global_types.pl" });
    perl_xml_enum_global_types.has_side_effects = true;
    perl_xml_enum_global_types.setName("xml_enum_global_types.pl");

    const perl_xml_enum_gen = b.addSystemCommand(&.{ "perl", "bin/xml_enum_gen.pl" });
    perl_xml_enum_gen.has_side_effects = true;
    perl_xml_enum_gen.setName("xml_enum_gen.pl");

    const perl_variable_setup = b.addSystemCommand(&.{ "perl", "bin/variable_setup.pl" });
    perl_variable_setup.has_side_effects = true;
    perl_variable_setup.setName("variable_setup.pl");

    // TODO: Clean up build scripts
    const git_rev_parse = b.addSystemCommand(&.{ "git", "rev-parse", "HEAD" });
    const git_version = b.addExecutable(.{
        .name = "git_version",
        .root_source_file = .{ .path = "./bin/git_version.zig" },
        .optimize = .ReleaseSafe,
        .use_llvm = false,
    });

    const auto_git_version = b.addRunArtifact(git_version);
    auto_git_version.addFileSourceArg(git_rev_parse.captureStdOut());
    auto_git_version.extra_file_dependencies = dll_sources; // TODO: Add XML files and build scripts?
    auto_git_version.has_side_effects = false;

    const generate_auto_git_version_h = b.addWriteFiles();
    generate_auto_git_version_h.addCopyFileToSource(auto_git_version.captureStdOut(), "DLLSources/autogenerated/AutoGitVersion.h");

    // TODO: Move all autogenerated sources into include path

    const perl = b.step("perl", "Execute pre-build Perl scripts");
    if (!skip_dll_export) {
        perl.dependOn(&perl_dll_export.step);
    }
    perl.dependOn(&perl_xml_validation.step);
    perl.dependOn(&perl_cpp_line_checker.step);
    perl.dependOn(&perl_xml_enum_global_types.step);
    perl.dependOn(&perl_xml_enum_gen.step);
    perl.dependOn(&perl_variable_setup.step);
    perl.dependOn(&generate_auto_git_version_h.step);

    const dll = b.addSharedLibrary(.{
        .name = "CvGameCoreDLL",
        .target = target,
        .optimize = optimize,
        .use_llvm = use_llvm,
        .use_lld = use_lld,
    });
    configure(dll, hardcoded_xml, final_release, profiling, oos_logging);
    dll.step.dependOn(perl);

    const combine_compile_commands_exe = b.addExecutable(.{
        .name = "combine_compile_commands",
        .root_source_file = .{ .path = "./bin/combine_compile_commands.zig" },
        .optimize = .ReleaseSafe,
        .use_llvm = false,
    });

    const combine_compile_commands = b.addRunArtifact(combine_compile_commands_exe);
    const comp_db = combine_compile_commands.captureStdOut();
    const install_comp_db = b.addWriteFiles();
    install_comp_db.addCopyFileToSource(comp_db, "compile_commands.json");
    const comp_db_step = b.step("comp_db", "Create compile_commands.json for tooling support");
    comp_db_step.dependOn(&install_comp_db.step);
    b.install_tls.step.dependOn(&install_comp_db.step);

    const tmp_comp_db_dir = try b.cache_root.join(b.allocator, &[_][]const u8{"tmp_comp_db"});
    try b.cache_root.handle.makePath("tmp_comp_db");

    for (dll_sources) |cpp_path| {
        const is_main = std.mem.eql(u8, cpp_path, main_dll_source);

        const cpp_name = std.fs.path.basename(cpp_path);
        const cpp = if (is_main) dll else b.addObject(.{
            .name = cpp_name,
            .target = target,
            .optimize = optimize,
            .use_llvm = use_llvm,
            .use_lld = use_lld,
        });
        configure(cpp, hardcoded_xml, final_release, profiling, oos_logging);
        cpp.step.dependOn(perl);

        // We need a static output path that's unique but consistent for each source file to properly cache it.
        const comp_db_name = b.fmt("{s}.json", .{cpp_name});
        const tmp_comp_db_path = b.pathJoin(&[_][]const u8{ tmp_comp_db_dir, comp_db_name });
        cpp.addCSourceFile(cpp_path, cpp_flags ++ &[_][]const u8{
            b.fmt("-MJ{s}", .{tmp_comp_db_path}),
        });

        const cached_comp_db = b.addWriteFiles();
        cached_comp_db.addCopyFile(std.Build.FileSource{ .path = tmp_comp_db_path }, comp_db_name);
        cached_comp_db.step.dependOn(&cpp.step);

        if (!is_main) {
            dll.addObjectFileSource(cpp.getOutputSource());
            dll.step.dependOn(&cached_comp_db.step);
        }

        if (!is_main) {
            const cpp_step = b.step(cpp_name, b.fmt("Compile '{s}'", .{cpp_name}));
            cpp_step.dependOn(&cpp.step);
            cpp_step.dependOn(&cached_comp_db.step);
        }

        combine_compile_commands.addFileSourceArg(cached_comp_db.getFileSource(comp_db_name) orelse @panic("shieee")); // TODO: Clean up panic message
    }

    for (library_paths) |library_path| {
        dll.addLibraryPath(library_path);
    }

    dll.linkSystemLibrary("msvcrt");
    dll.linkSystemLibrary("msvcprt");
    dll.linkSystemLibrary("oldnames"); // TODO: Can this be replaced by `/ALTERNATENAME`?

    dll.linkSystemLibrary("kernel32");
    dll.linkSystemLibrary("winmm");
    dll.linkSystemLibrary("user32");
    dll.linkSystemLibrary("shell32");

    dll.linkSystemLibrary("boost_python-vc71-mt-1_32");
    dll.linkSystemLibrary("python24");

    dll.linkSystemLibrary("tbb");
    dll.linkSystemLibrary("tbbmalloc");

    // Clang is generating calls to the new C++ exception handler, but MSVC++ 2003 does not provide the new one.
    // Instead, we're just creating a shim handler that calls MSVC++ 2003's.
    const shim = b.addObject(.{
        .name = "shim",
        .root_source_file = .{ .path = "./DLLSources/shim.zig" },
        .target = target,
        // Allowing `.Debug` will try importing things that we don't have.
        .optimize = .ReleaseFast,
    });
    dll.addObject(shim);

    dll.strip = false;

    // TODO: Replace with more proper installation step, probably using prefix
    const copy_dll = b.addSystemCommand(&.{"cp"});
    copy_dll.addFileSourceArg(dll.getOutputSource());
    copy_dll.addFileSourceArg(dll.getOutputPdbSource());
    copy_dll.addArg("/home/wrs/.local/share/Steam/steamapps/common/Civilization IV Colonization/Mods/WeThePeople/Assets/");
    copy_dll.setName("Copy CvGameCoreDLL into Mods/WeThePeople");

    b.default_step.dependOn(&copy_dll.step);
}

/// TODO: Clean up `configure` to be separate for compilation and linking.
fn configure(obj: *std.Build.CompileStep, hardcoded_xml: bool, final_release: bool, profiling: bool, oos_logging: bool) void {
    // TODO: Figure out how we want to link things.

    obj.linker_dynamicbase = false;
    // obj.dll_export_fns = false;
    // obj.link_gc_sections = true; // TODO: Does this break anything?
    obj.link_function_sections = true;
    obj.want_lto = final_release;
    // obj.omit_frame_pointer = final_release;
    obj.single_threaded = false;

    obj.disable_sanitize_c = true; //final_release;

    // TODO: Do we need Zig's CRT?
    obj.bundle_compiler_rt = false;

    // TODO: Clean up include paths
    obj.addSystemIncludePath("../../Compiler/Microsoft SDKs/Windows/v6.0/Include");

    obj.addSystemIncludePath("../../Compiler/Microsoft Visual C++ Toolkit 2003/include");

    obj.addIncludePath("../../Compiler/lib/Boost-1.32.0/include");

    obj.defineCMacro("uintptr_t", "DWORD_PTR"); // `pyport.h` wants to use `uintptr_t`
    obj.addIncludePath("../../Compiler/lib/Python24/include");

    obj.defineCMacro("__TBBMALLOC_NO_IMPLICIT_LINKAGE", null); // Without this, TBB will try linking itself via `#pragma comment(lib, ...)`
    obj.addIncludePath("./DLLSources/tbb"); // TODO: Move out of source tree.

    // TODO: Figure out which macro defines are provided by Zig, which are provided by Clang, and which we need to provide.
    obj.defineCMacro("WIN32", null);
    obj.defineCMacro("_WINDOWS", null);
    obj.defineCMacro("_DLL", null);
    obj.defineCMacro("_MT", null);
    // obj.defineCMacro("_UNICODE", null);
    // obj.defineCMacro("UNICODE", null);

    // TODO: Figure out how we want to propagate debug mode to C++ without misconfiguring library include headers.
    if (obj.optimize == .Debug) {
        // obj.defineCMacro("_DEBUG", null);
    } else {
        //
    }

    // TODO: What does this do exactly?
    obj.defineCMacro("CHECK_GLOBAL_CONSTANTS", null);

    if (hardcoded_xml) {
        // TODO: Clean up how `HARDCODE_XML_VALUES` gets handled in the C++.
        obj.defineCMacro("HARDCODE_XML_VALUES", null);
    }

    if (final_release) {
        obj.defineCMacro("FINAL_RELEASE", null);
    } else {
        obj.defineCMacro("FASSERT_ENABLE", null);
    }

    if (profiling) {
        obj.defineCMacro("PROFILING_ENABLED", null);
    }

    if (oos_logging) {
        obj.defineCMacro("GLOBAL_DEFINE_USE_OOS_LOGGING", null);
    }

    // TODO: Do we need/want these? What's the best way to include Boost in this setup?
    // dll.defineCMacro("BOOST_USE_WINDOWS_H", null);
    // dll.defineCMacro("__CORRECT_ISO_CPP_STRING_H_PROTO", null);

    // TODO: Figure out how to best handle `_MSC_VER`. What's the default value for `_MSC_VER` with Clang?
    // obj.defineCMacro("_MSC_VER", "1310");

    // TODO: Consider setting `__INTEL_COMPILER` to convince TBB to not treat us like we're retarded (MSVC).
}

/// Clang flags for compiling each C++ source file.
/// TODO: Split out linker flags from compiler flags.
const cpp_flags = &[_][]const u8{
    // TODO: Update the C++ version once we've cleaned up both the codebase and the Microsoft include headers as well as verified that MSVC++ 2003 is compatible with any language-level changes.
    "-std=c++2b",
    "-Wno-c++11-extensions",
    "-Wno-c++98-compat",

    // TODO: Re-enable these warnings once both the codebase and the Microsoft include headers have been cleaned up to be spec compliant.
    "-Wno-microsoft-extra-qualification",
    "-Wno-microsoft-template-shadow",
    "-Wno-microsoft-template",
    "-Wno-microsoft-enum-forward-reference",
    // TODO: Disable these workarounds once both the cosebase and the Microsoft include headesr have been cleaned up to be spec compliant.
    "-fms-extensions",
    "-fms-compatibility",
    "-fdelayed-template-parsing",

    // TODO: Fix EnumMap code
    "-Wno-deprecated-anon-enum-enum-conversion",

    // TODO: Re-enable these warnings once the codebase isn't shit.
    // "-Wno-c++11-compat-deprecated-writable-strings",
    // "-Wno-deprecated-register",
    // "-Wno-switch",
    // "-Wno-non-pod-varargs",

    // Boost: Unknown compiler version
    // TODO: Also linker flag pragmas?
    "-Wno-#pragma-messages",
    "-Wno-comment",

    // Python
    "-Wno-register",

    // For some reason, Zig is passing an unused argument to Clang.
    // Whenever we change of these flags, we should try disabling this to verify that they're being used as expected.
    // See: https://github.com/ziglang/zig/blob/b677b3627818edc24828f36f8269a3c3843703a1/src/Compilation.zig#L4248
    "-Wno-unused-command-line-argument",

    // Troubleshooting
    // TODO: Remove these before committing.
    "-Wno-everything",
    // "-Weverything",
    // "-Werror",
    // "-ferror-limit=99999999",

    // Resolves missing symbol linker errors
    // MSVC++ 2003 did not have thread-safe initialization of statics
    // TODO: Figure out how to best handle thread bullshit in MSVC++ 2003.
    "-fno-threadsafe-statics",

    // Original Makefile uses MSVC's /EHsc which disables SEH but enables C++ exceptions
    "-fno-async-exceptions",
    "-fcxx-exceptions",
    "-fexceptions", // TODO: Redundant?

    // TODO: Figure out how to enable the LAA flag in the final DLL. Clang/LLD is failing to do so, so we likely need to create a post-build step.
    // "-Wl,--large-address-aware",

    // Zig will automatically define `_DEBUG` and `NDEBUG` anyways, so let's avoid redefining it.
    // See: https://github.com/ziglang/zig/blob/b677b3627818edc24828f36f8269a3c3843703a1/src/Compilation.zig#L4378
    // See: https://github.com/ziglang/zig/blob/b677b3627818edc24828f36f8269a3c3843703a1/src/Compilation.zig#L4391
    "-fno-debug-macro",
};

/// TODO: Figure out where these should be long-term.
const library_paths = &[_][]const u8{
    "../../Compiler/Microsoft SDKs/Windows/v6.0/Lib",
    "../../Compiler/Microsoft Visual C++ Toolkit 2003/lib",
    "../../Compiler/lib/Boost-1.32.0/libs",
    "../../Compiler/lib/Python24/libs",
    "./tbb",
};

const main_dll_source = "./DLLSources/CvGameCoreDLL.cpp";
const dll_sources = &[_][]const u8{
    main_dll_source,
    "./DLLSources/AlertWindow.cpp",
    "./DLLSources/Autogenerated.cpp",
    "./DLLSources/BetterBTSAI.cpp",
    "./DLLSources/CvArea.cpp",
    "./DLLSources/CvAreaSavegame.cpp",
    "./DLLSources/CvArtFileMgr.cpp",
    "./DLLSources/CvCity.cpp",
    "./DLLSources/CvCityAI.cpp",
    "./DLLSources/CvCityAISavegame.cpp",
    "./DLLSources/CvCitySavegame.cpp",
    "./DLLSources/CvCityYields.cpp",
    "./DLLSources/CvDLLButtonPopup.cpp",
    "./DLLSources/CvDLLEngineIFaceBase.cpp",
    "./DLLSources/CvDLLEntity.cpp",
    "./DLLSources/CvDLLInterfaceIFaceBase.cpp",
    "./DLLSources/CvDLLPython.cpp",
    "./DLLSources/CvDLLWidgetData.cpp",
    "./DLLSources/CvDeal.cpp",
    "./DLLSources/CvDealSavegame.cpp",
    "./DLLSources/CvDiploParameters.cpp",
    "./DLLSources/CvDiploParametersSavegames.cpp",
    "./DLLSources/CvFractal.cpp",
    "./DLLSources/CvGame.cpp",
    "./DLLSources/CvGameAI.cpp",
    "./DLLSources/CvGameAISavegame.cpp",
    "./DLLSources/CvGameCoreUtils.cpp",
    "./DLLSources/CvGameSavegame.cpp",
    "./DLLSources/CvGameTextMgr.cpp",
    "./DLLSources/CvGlobalConstants.cpp",
    "./DLLSources/CvGlobals.cpp",
    "./DLLSources/CvGlobalsEnumSetup.cpp",
    "./DLLSources/CvHallOfFameInfo.cpp",
    "./DLLSources/CvInfoWater.cpp",
    "./DLLSources/CvInfos.cpp",
    "./DLLSources/CvInitCore.cpp",
    "./DLLSources/CvMap.cpp",
    "./DLLSources/CvMapGenerator.cpp",
    "./DLLSources/CvMapSavegame.cpp",
    "./DLLSources/CvPlayer.cpp",
    "./DLLSources/CvPlayerAI.cpp",
    "./DLLSources/CvPlayerAISavegame.cpp",
    "./DLLSources/CvPlayerCivEffect.cpp",
    "./DLLSources/CvPlayerSavegame.cpp",
    "./DLLSources/CvPlot.cpp",
    "./DLLSources/CvPlotFunctions.cpp",
    "./DLLSources/CvPlotSavegame.cpp",
    "./DLLSources/CvPopupInfo.cpp",
    "./DLLSources/CvPopupInfoSavegame.cpp",
    "./DLLSources/CvPopupReturn.cpp",
    "./DLLSources/CvRandom.cpp",
    "./DLLSources/CvReplayInfo.cpp",
    "./DLLSources/CvReplayMessage.cpp",
    "./DLLSources/CvReplayMessageSavegame.cpp",
    "./DLLSources/CvSavegame.cpp",
    "./DLLSources/CvSelectionGroup.cpp",
    "./DLLSources/CvSelectionGroupAI.cpp",
    "./DLLSources/CvSelectionGroupAISavegame.cpp",
    "./DLLSources/CvSelectionGroupSavegame.cpp",
    "./DLLSources/CvStructs.cpp",
    "./DLLSources/CvTalkingHeadMessage.cpp",
    "./DLLSources/CvTalkingHeadMessageSavegame.cpp",
    "./DLLSources/CvTeam.cpp",
    "./DLLSources/CvTeamAI.cpp",
    "./DLLSources/CvTeamAISavegame.cpp",
    "./DLLSources/CvTeamSavegame.cpp",
    "./DLLSources/CvTradeRoute.cpp",
    "./DLLSources/CvTradeRouteGroup.cpp",
    "./DLLSources/CvTradeRouteGroupSavegame.cpp",
    "./DLLSources/CvTradeRouteSavegame.cpp",
    "./DLLSources/CvUnit.cpp",
    "./DLLSources/CvUnitAI.cpp",
    "./DLLSources/CvUnitAISavegame.cpp",
    "./DLLSources/CvUnitSavegame.cpp",
    "./DLLSources/CvXMLLoadUtility.cpp",
    "./DLLSources/CvXMLLoadUtilityGet.cpp",
    "./DLLSources/CvXMLLoadUtilityInit.cpp",
    "./DLLSources/CvXMLLoadUtilitySet.cpp",
    "./DLLSources/CyArea.cpp",
    "./DLLSources/CyAreaInterface.cpp",
    "./DLLSources/CyArgsList.cpp",
    "./DLLSources/CyArtFileMgr.cpp",
    "./DLLSources/CyArtFileMgrInterface.cpp",
    "./DLLSources/CyCity.cpp",
    "./DLLSources/CyCityInterface1.cpp",
    "./DLLSources/CyCityInterface2.cpp",
    "./DLLSources/CyCityInterface3.cpp",
    "./DLLSources/CyCityInterface4.cpp",
    "./DLLSources/CyCityInterface5.cpp",
    "./DLLSources/CyData.cpp",
    "./DLLSources/CyDataInterface.cpp",
    "./DLLSources/CyDeal.cpp",
    "./DLLSources/CyDealInterface.cpp",
    "./DLLSources/CyEnumsInterface.cpp",
    "./DLLSources/CyGame.cpp",
    "./DLLSources/CyGameCoreUtils.cpp",
    "./DLLSources/CyGameCoreUtilsInterface.cpp",
    "./DLLSources/CyGameInterface1.cpp",
    "./DLLSources/CyGameInterface2.cpp",
    "./DLLSources/CyGameInterface3.cpp",
    "./DLLSources/CyGameTextMgr.cpp",
    "./DLLSources/CyGameTextMgrInterface.cpp",
    "./DLLSources/CyGlobalContext.cpp",
    "./DLLSources/CyGlobalContextInterface1.cpp",
    "./DLLSources/CyGlobalContextInterface2.cpp",
    "./DLLSources/CyGlobalContextInterface3.cpp",
    "./DLLSources/CyGlobalContextInterface4.cpp",
    "./DLLSources/CyGlobalContextInterface5.cpp",
    "./DLLSources/CyGlobalContextInterface6.cpp",
    "./DLLSources/CyGlobalContextInterface7.cpp",
    "./DLLSources/CyHallOfFameInfo.cpp",
    "./DLLSources/CyHallOfFameInterface.cpp",
    "./DLLSources/CyInfoInterface1.cpp",
    "./DLLSources/CyInfoInterface2.cpp",
    "./DLLSources/CyInfoInterface3.cpp",
    "./DLLSources/CyInfos.cpp",
    "./DLLSources/CyMap.cpp",
    "./DLLSources/CyMapGenerator.cpp",
    "./DLLSources/CyMapGeneratorInterface.cpp",
    "./DLLSources/CyMapInterface1.cpp",
    "./DLLSources/CyMapInterface2.cpp",
    "./DLLSources/CyPlayer.cpp",
    "./DLLSources/CyPlayerInterface1.cpp",
    "./DLLSources/CyPlayerInterface2.cpp",
    "./DLLSources/CyPlayerInterface3.cpp",
    "./DLLSources/CyPlayerInterface4.cpp",
    "./DLLSources/CyPlot.cpp",
    "./DLLSources/CyPlotInterface1.cpp",
    "./DLLSources/CyPlotInterface2.cpp",
    "./DLLSources/CyRandomInterface.cpp",
    "./DLLSources/CyReplayInfo.cpp",
    "./DLLSources/CySelectionGroup.cpp",
    "./DLLSources/CySelectionGroupInterface.cpp",
    "./DLLSources/CyStructsInterface1.cpp",
    "./DLLSources/CyTeam.cpp",
    "./DLLSources/CyTeamInterface.cpp",
    "./DLLSources/CyTradeRoute.cpp",
    "./DLLSources/CyTradeRouteGroup.cpp",
    "./DLLSources/CyTradeRouteGroupInterface.cpp",
    "./DLLSources/CyTradeRouteInterface.cpp",
    "./DLLSources/CyUnit.cpp",
    "./DLLSources/CyUnitInterface1.cpp",
    "./DLLSources/CyUnitInterface2.cpp",
    "./DLLSources/CyUserSettings.cpp",
    "./DLLSources/CyUserSettingsInterface.cpp",
    "./DLLSources/EXE_interface.cpp",
    "./DLLSources/FAssert.cpp",
    "./DLLSources/FDialogTemplate.cpp",
    "./DLLSources/InfoArray.cpp",
    "./DLLSources/JustInTimeArray.cpp",
    "./DLLSources/JustInTime_Features.cpp",
    "./DLLSources/KmodPathFinder.cpp",
    "./DLLSources/OpenURL.cpp",
    "./DLLSources/PlayerHelperFunctions.cpp",
    "./DLLSources/Profile.cpp",
    "./DLLSources/StartupErrorChecking.cpp",
    "./DLLSources/TestEnumMap.cpp",
    "./DLLSources/UserSettings.cpp",
    "./DLLSources/XMLLengthSet.cpp",
    "./DLLSources/_precompile.cpp",
    "./DLLSources/tinyxml2.cpp",
};
